season: "2015"
casting_complete: false

# Site settings
title: Post Playhouse
email: don@happycollision.com
twitter: postplayhouse
facebook: post.playhouse
description: >
  Post Playhouse is Northwestern Nebraska's premiere venue for live theatre, producing several musicals running in a repertory schedule every summer by utilizing the talent of creative professionals from across the country and nearby. Post Playhouse, Inc. mounts its productions at the theatre in Fort Robinson State Park.
baseurl: ""
url: "http://postplayhouse.com" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart']

permalink: /news/:year/:month/:day/:title/

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
  
timezone:       US/Mountain
locale:         en_us
icon:           /images/post-playhouse-logo.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      share: true